### ISSUE TITLE
Create installation if not found

### ISSUE THREAD

**Issue by StefanoMartin** [Wappsto/wappsto-cli#199]
Situation:

- Version is already created
- Installation has been uninstalled

Expected:

- npx wapp serve <--- It should recreate the installation, it does not do that
- npx wapp create (connected with existing version) <--- It should recreate the installation, it does not do that

I mark as bug because it stops normal users to continue to develop their own installation if the installation has been deleted for any reason.

**Comment by AndreasBomholtz** [comment]
Same as #181
